from django.contrib import admin
from .models import Doctor, Patient, Appointment

# This class customizes the look of the Appointment table in the admin panel
class AppointmentAdmin(admin.ModelAdmin):
    # 1. Columns shown in the main list view
    list_display = ('patient', 'doctor', 'date', 'time_slot', 'ai_predicted_disease','ai_precaution')
    
    # 2. Add a search bar to find patients by name or ID
    search_fields = ('patient__name', 'patient__age')
    
    # 3. Add a filter sidebar to quickly see appointments by date or status
    list_filter = ('date', 'doctor')

    # 4. Make AI fields "Read-Only" so staff can't accidentally change the AI's diagnosis
    readonly_fields = ('ai_predicted_disease', 'ai_precaution')

    # 5. Group the data into sections for a cleaner look
    fieldsets = (
        ('Patient & Schedule', {
            'fields': ('patient', 'doctor', 'date', 'time_slot')
        }),
        ('Medical Analysis (AI Generated)', {
            'fields': ('symptoms', 'ai_predicted_disease', 'ai_precaution'),
            'description': 'These fields are generated by the Transformer model based on symptoms.'
        }),
    )

# Register the models
admin.site.register(Doctor)
admin.site.register(Patient)
admin.site.register(Appointment, AppointmentAdmin)