# Generated by Django 6.0.4 on 2026-04-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_reg_number_patient_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Age',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(help_text='Enter symptoms (e.g., chest pain, headache)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ai_predicted_disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
