# Generated by Django 6.0.4 on 2026-04-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_address_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ai_predicted_disease',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ai_precaution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ai_predicted_disease',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
